<?php
return array(
    'USER' => 'ataur',
    'HOME' => '/home/ataur',
    'HTTP_CACHE_CONTROL' => 'max-age=0',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_REFERER' => 'http://localhost/falgun-skeleton/',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0',
    'HTTP_HOST' => 'localhost',
    'PATH_INFO' => '',
    'PATH_TRANSLATED' => '/home/ataur/server/falgun-skeleton/public/index.php',
    'SCRIPT_FILENAME' => '/home/ataur/server/falgun-skeleton/public/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => 'localhost',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '127.0.0.1',
    'REMOTE_PORT' => '37716',
    'REMOTE_ADDR' => '127.0.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.18.0',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/home/ataur/server',
    'DOCUMENT_URI' => '/falgun-skeleton/public/index.php',
    'REQUEST_URI' => '/falgun-skeleton/public/',
    'SCRIPT_NAME' => '/falgun-skeleton/public/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/falgun-skeleton/public/index.php',
    'REQUEST_TIME_FLOAT' => 1598448444.110924,
    'REQUEST_TIME' => 1598448444,
);
